packages:
  - packages/*
minimumReleaseAgeExclude:
  - '@pawnary/*'
catalogMode: prefer
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: true
catalog:
  '@jsonjoy.com/json-pack': ^18.28.0
  '@msgpack/msgpack': ^3.1.3
  '@pawnary/oxfmt-config': 0.0.0-commit.46c4a819fae0ab33ac972df5568e165efce9add9
  '@pawnary/oxlint-config': 0.0.0-commit.46c4a819fae0ab33ac972df5568e165efce9add9
  '@pawnary/tsdown-fix-exports': 0.0.1-next.ff1c982bcc87e5c8032af934ee04b0fedb4e3793
  '@types/bun': ^1.3.14
  '@types/node': ^26.2.0
  console-table-printer: ^2.16.1
  jsdom: ^30.0.1
  msgpackr: ^2.0.5
  oxfmt: ^0.64.0
  oxlint: ^1.79.0
  oxlint-tsgolint: ^7.0.2001
  publint: ^0.3.23
  tinybench: ^6.1.3
  tsdown: ^0.22.14
  typescript: ^7.0.2
  vitest: ^4.1.11
