name: 'Continuous Integration'
on:
  pull_request:
    branches:
      - master
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
  oxfmt:
    runs-on: ubuntu-latest
    needs:
      - dependencies
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - name: Run oxfmt check
        run: pnpm run fmt
  oxlint:
    runs-on: ubuntu-latest
    needs:
      - dependencies
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - name: Run oxlint check
        run: pnpm run lint
  tsc:
    runs-on: ubuntu-latest
    needs:
      - dependencies
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - name: Run tsc check
        run: pnpm run tsc:check
  vitest:
    runs-on: ubuntu-latest
    needs:
      - dependencies
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - name: Run vitest check
        run: pnpm run test:ci
  build:
    runs-on: ubuntu-latest
    needs:
      - dependencies
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - name: Run build
        run: pnpm run build
  build-docs:
    runs-on: ubuntu-latest
    needs:
      - dependencies
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup
      - name: Run build docs
        run: pnpm run build:docs
